In [1]:
import os
import pandas as pd
import numpy as np
os.chdir("C:\\Users\\marci\\dev\\Week2_Proj_Energy\\dataproc")

In [3]:
df = pd.read_csv("raw\\open_energy_data.csv")
df.head()

,country,year,iso_code,population,gdp,biofuel_cons_change_pct,biofuel_cons_change_twh,biofuel_cons_per_capita,biofuel_consumption,biofuel_elec_per_capita,...,solar_share_elec,solar_share_energy,wind_cons_change_pct,wind_cons_change_twh,wind_consumption,wind_elec_per_capita,wind_electricity,wind_energy_per_capita,wind_share_elec,wind_share_energy
0,Afghanistan,1900,AFG,4832414.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,1901,AFG,4879685.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afghanistan,1902,AFG,4935122.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afghanistan,1903,AFG,4998861.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,1904,AFG,5063419.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
df_clean = df[df["year"]>=2011]

In [8]:
df_clean =df_clean.replace(np.nan, " ")

In [18]:
df_clean.shape

(3152, 129)

In [16]:
#df_clean.to_sql("open_energy_data_clean")

df_clean.to_csv("open_energy_data_clean.csv",index=False,na_rep='NULL')

In [11]:
for colu in df_clean.columns:
    df_clean[colu]
    if colu != "country" and colu != "year" and colu != "iso_code":
        df_clean[colu] = df_clean[colu].astype(float)
df_clean.to_csv("open_energy_data_clean.csv",index=False)

ValueError: could not convert string to float: ' '

In [10]:
df_2 = df_clean.iloc[:10]
df_2.to_csv("open_energy_data_test.csv",index=False)

In [12]:
df_clean.shape

(6131, 129)

In [40]:
df_clean[df_clean["country"]=="Nigeria"]

,country,year,iso_code,population,gdp,biofuel_cons_change_pct,biofuel_cons_change_twh,biofuel_cons_per_capita,biofuel_consumption,biofuel_elec_per_capita,...,solar_share_elec,solar_share_energy,wind_cons_change_pct,wind_cons_change_twh,wind_consumption,wind_elec_per_capita,wind_electricity,wind_energy_per_capita,wind_share_elec,wind_share_energy
13608,Nigeria,2001,NGA,126152680.0,2.933719e+11,0.0,0.0,0.0,0.0,0.079,...,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13609,Nigeria,2002,NGA,129583032.0,3.448372e+11,0.0,0.0,0.0,0.0,0.077,...,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13610,Nigeria,2003,NGA,133119808.0,3.872862e+11,0.0,0.0,0.0,0.0,0.075,...,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13611,Nigeria,2004,NGA,136756848.0,4.388190e+11,0.0,0.0,0.0,0.0,0.146,...,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13612,Nigeria,2005,NGA,140490720.0,4.818059e+11,0.0,0.0,0.0,0.0,0.071,...,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13613,Nigeria,2006,NGA,144329760.0,5.276463e+11,0.0,0.0,0.0,0.0,0.069,...,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13614,Nigeria,2007,NGA,148294032.0,5.810247e+11,0.0,0.0,0.0,0.0,0.067,...,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13615,Nigeria,2008,NGA,152382512.0,6.389428e+11,0.0,0.0,0.0,0.0,0.066,...,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13616,Nigeria,2009,NGA,156595744.0,7.099804e+11,0.0,0.0,0.0,0.0,0.064,...,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13617,Nigeria,2010,NGA,160952864.0,8.100680e+11,0.0,0.0,0.0,0.0,0.124,...,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13618,Nigeria,2011,NGA,165463744.0,8.711909e+11,0.0,0.0,0.0,0.0,0.121,...,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13619,Nigeria,2012,NGA,170075936.0,9.096492e+11,0.0,0.0,0.0,0.0,0.118,...,0.073,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13620,Nigeria,2013,NGA,174726128.0,9.599389e+11,0.0,0.0,0.0,0.0,0.114,...,0.073,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13621,Nigeria,2014,NGA,179379024.0,1.021286e+12,0.0,0.0,0.0,0.0,0.111,...,0.065,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13622,Nigeria,2015,NGA,183995776.0,1.048705e+12,0.0,0.0,0.0,0.0,0.109,...,0.097,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13623,Nigeria,2016,NGA,188666928.0,1.032470e+12,0.0,0.0,0.0,0.0,0.106,...,0.094,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13624,Nigeria,2017,NGA,193495904.0,1.040792e+12,0.0,0.0,0.0,0.0,0.103,...,0.091,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13625,Nigeria,2018,NGA,198387616.0,1.060806e+12,0.0,0.0,0.0,0.0,0.101,...,0.094,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13626,Nigeria,2019,NGA,203304496.0,0.000000e+00,0.0,0.0,0.0,0.0,0.098,...,0.126,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13627,Nigeria,2020,NGA,208327408.0,0.000000e+00,0.0,0.0,0.0,0.0,0.096,...,0.134,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13628,Nigeria,2021,NGA,213401328.0,0.000000e+00,0.0,0.0,0.0,0.0,0.094,...,0.159,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [29]:
df_FR = df_clean[df_clean["country"]=="France"]

for colu in df_FR.columns:
    df_FR[colu]
    if colu != "country" and colu != "year" and colu != "iso_code":
        df_FR[colu] = df_FR[colu].astype(float)

df_FR.to_csv("open_energy_FR.csv", index=False)

C:\Users\marci\AppData\Local\Temp\ipykernel_6272\1645148989.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_FR[colu] = df_FR[colu].astype(float)

In [15]:
df_FR.shape

(21, 129)

In [42]:
df_rd = pd.read_csv("..\\data\\COUNTRY_BUDGETS\\COUNTRY_BUDGETS.TXT", delimiter=r"\s+",
header=None, na_values="..")

In [43]:
df_rd.head()
df_rd.rename(columns={0:"country", 1:"rd_product",2:"efficiency",3:"year",4:"total"}, inplace=True)

In [44]:
df_rd = df_rd[df_rd["year"]>=2011]

In [57]:
df_rd.head()

     country rd_product  efficiency  year   total
19  AUSTRALI     GOVTRD  EFFICIENCY  2011  98.931
20  AUSTRALI     GOVTRD  EFFICIENCY  2012  70.573
21  AUSTRALI     GOVTRD  EFFICIENCY  2013  62.007
22  AUSTRALI     GOVTRD  EFFICIENCY  2014  29.749
23  AUSTRALI     GOVTRD  EFFICIENCY  2015  28.836

In [65]:
df_fr= df_rd[df_rd["total"]>0]
df_fr

          country rd_product  efficiency  year    total
19       AUSTRALI     GOVTRD  EFFICIENCY  2011   98.931
20       AUSTRALI     GOVTRD  EFFICIENCY  2012   70.573
21       AUSTRALI     GOVTRD  EFFICIENCY  2013   62.007
22       AUSTRALI     GOVTRD  EFFICIENCY  2014   29.749
23       AUSTRALI     GOVTRD  EFFICIENCY  2015   28.836
...           ...        ...         ...   ...      ...
2311953    BRAZIL    RDDEURO       TOTAL  2016  523.046
2311954    BRAZIL    RDDEURO       TOTAL  2017  598.363
2311955    BRAZIL    RDDEURO       TOTAL  2018  695.343
2311956    BRAZIL    RDDEURO       TOTAL  2019  634.703
2311957    BRAZIL    RDDEURO       TOTAL  2020  546.784

[154322 rows x 5 columns]

In [56]:
df_rd.to_csv("..\\data\\rd_country_budgets_2011_2021.csv",index=False,na_rep=-1)

In [50]:
df_rd.iloc[28,:]

country       AUSTRALI
rd_product      GOVTRD
efficiency    111INDTE
year              2011
total              NaN
Name: 136, dtype: object

In [5]:
df_co = pd.read_csv("data_CO2_clean.csv",sep=";")
df_co.head()
df_co.to_csv("..\\data\\data_CO2_clean.csv",index=False,na_rep=-1)